/**
 * Swagger RESGEN
 * This is a API REST field for RESGEN proyect.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.resgen.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;


/**
 * Generate
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-18T19:09:46.109+02:00")
public class Generate   {
  @SerializedName("resource")
  private Resource resource = null;

  @SerializedName("systems")
  private Systems systems = null;

  @SerializedName("tarrif")
  private Tariff tarrif = null;

  @SerializedName("customer")
  private Customer customer = null;

  /**
   * Gets or Sets env
   */
  public enum EnvEnum {
    @SerializedName("UAT")
    UAT("UAT"),
    
    @SerializedName("INT")
    INT("INT");

    private String value;

    EnvEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("env")
  private EnvEnum env = null ;

  /**
   * Gets or Sets profile
   */
  public enum ProfileEnum {
    @SerializedName("BAU")
    BAU("BAU"),
    
    @SerializedName("CIMA")
    CIMA("CIMA");

    private String value;

    ProfileEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("profile")
  private ProfileEnum profile = ProfileEnum.BAU;
  
//  public Generate () {
//	   Resource resource = new Resource();
//	   String msisdn = null;;
//	   resource.setMsisdn(msisdn);
//	   String imsi = null;
//	   resource.setImsi(imsi);
//	   String iccid = null;
//	   resource.setIccid(iccid);
//	   this.setResource(resource);
//	   Systems systems = new Systems();
//	   this.setSystems(systems);
//	   Tariff tarrif = new Tariff();
//	   this.setTarrif(tarrif);
//	   Customer customer = new Customer();
//	   this.setCustomer(customer);
//	  }


  public Generate resource(Resource resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Resource getResource() {
    return resource;
  }

  public void setResource(Resource resource) {
    this.resource = resource;
  }

  public Generate systems(Systems systems) {
    this.systems = systems;
    return this;
  }

   /**
   * Get systems
   * @return systems
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Systems getSystems() {
    return systems;
  }

  public void setSystems(Systems systems) {
    this.systems = systems;
  }

  public Generate tarrif(Tariff tarrif) {
    this.tarrif = tarrif;
    return this;
  }

   /**
   * Get tarrif
   * @return tarrif
  **/
  @ApiModelProperty(example = "null", value = "")
  public Tariff getTarrif() {
    return tarrif;
  }

  public void setTarrif(Tariff tarrif) {
    this.tarrif = tarrif;
  }

  public Generate customer(Customer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.customer = customer;
  }

  public Generate env(EnvEnum env) {
    this.env = env;
    return this;
  }

   /**
   * Get env
   * @return env
  **/
  @ApiModelProperty(example = "null", value = "")
  public EnvEnum getEnv() {
    return env;
  }

  public void setEnv(EnvEnum env) {
    this.env = env;
  }

  public Generate profile(ProfileEnum profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public ProfileEnum getProfile() {
    return profile;
  }

  public void setProfile(ProfileEnum profile) {
    this.profile = profile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Generate generate = (Generate) o;
    return Objects.equals(this.resource, generate.resource) &&
        Objects.equals(this.systems, generate.systems) &&
        Objects.equals(this.tarrif, generate.tarrif) &&
        Objects.equals(this.customer, generate.customer) &&
        Objects.equals(this.env, generate.env) &&
        Objects.equals(this.profile, generate.profile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resource, systems, tarrif, customer, env, profile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Generate {\n");
    
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    systems: ").append(toIndentedString(systems)).append("\n");
    sb.append("    tarrif: ").append(toIndentedString(tarrif)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

