/**
 * Swagger RESGEN
 * This is a API REST field for RESGEN proyect.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.resgen.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Tariff
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-18T19:09:46.109+02:00")
public class Tariff   {
  @SerializedName("shdes")
  private String shdes = null;

  /**
   * Gets or Sets market
   */
  public enum MarketEnum {
    @SerializedName("res")
    RES("res"),
    
    @SerializedName("lc")
    LC("lc"),
    
    @SerializedName("pre")
    PRE("pre"),
    
    @SerializedName("love")
    LOVE("love"),
    
    @SerializedName("emp")
    EMP("emp"),
    
    @SerializedName("mfo")
    MFO("mfo");

    private String value;

    MarketEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("market")
  private MarketEnum market = MarketEnum.RES;

  public Tariff shdes(String shdes) {
    this.shdes = shdes;
    return this;
  }

   /**
   * Get shdes
   * @return shdes
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getShdes() {
    return shdes;
  }

  public void setShdes(String shdes) {
    this.shdes = shdes;
  }

  public Tariff market(MarketEnum market) {
    this.market = market;
    return this;
  }

   /**
   * Get market
   * @return market
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public MarketEnum getMarket() {
    return market;
  }

  public void setMarket(MarketEnum market) {
    this.market = market;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tariff tariff = (Tariff) o;
    return Objects.equals(this.shdes, tariff.shdes) &&
        Objects.equals(this.market, tariff.market);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shdes, market);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tariff {\n");
    
    sb.append("    shdes: ").append(toIndentedString(shdes)).append("\n");
    sb.append("    market: ").append(toIndentedString(market)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

